// <auto-generated />
namespace ResultsExamination.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddTables_Conditioner_LightSourse_EngineringTechnicalProvision : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTables_Conditioner_LightSourse_EngineringTechnicalProvision));
        
        string IMigrationMetadata.Id
        {
            get { return "202202241720452_AddTables_Conditioner_LightSourse_EngineringTechnicalProvision"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
